pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build') {
      steps {
        sh 'docker compose build'
      }
    }

    stage('Smoke Test') {
      steps {
        sh 'docker compose up -d'
        sh 'sleep 10'
        sh 'bash tests/smoke.sh'
      }
    }
  }

  post {
    always {
      sh 'docker compose down -v || true'
    }
  }
}
